fix: remove the crisis module key from keys list (#125)
The key was initially kept to perform the deletion of the store, but
then the node is not able to restart because the store was expected to
have the key.

Error: `failed to load latest version: failed to load latest version:
version of store crisis mismatch root store's version; expected 45 got
0; new stores should be added using StoreUpgrades`